#!/usr/bin/env bash
#this Bash script displays Best School 10 times, but for the 9th iteration, it displays Best School which is followed  Hi on a new line.
n=1
until [ $n -gt 10 ]
do 
  echo "Best School"
  ((n++))
done
